name: Telegram Perpetual Bot

on:
  schedule:
    - cron: "0 */5 * * *"  # جدولة كل 5 ساعات
  workflow_dispatch:

concurrency:
  group: telegram_bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install --upgrade python-telegram-bot yt-dlp
      - name: Run Telegram Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          python -u bot.py
